[build]
builder = "NIXPACKS"
buildCommand = "cd DeepFocus/backend && npm ci"

[deploy]
startCommand = "cd DeepFocus/backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
